[tool.poetry]
name = "bakabot"
version = "0.1.0"
description = "bakabot"
authors = ["flpFlan"]
repository = "https://github.com/flpFlan/bakabot"

[tool.poetry.dependencies]
python = "^3.11"
websockets = "^11.0.1"
pycryptodome = "^3.17"
requests = "^2.28.2"
APScheduler = "^3.10.1"
sqlalchemy = "^2.0.9"
redis = "^4.5.4"

[[tool.poetry.source]]
name = "tencent"
url = "https://mirrors.cloud.tencent.com/pypi/simple"